eureka:   
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
     serviceUrl:
         defaultZone: http://localhost:8761/eureka
     instance:
         hostname: localhost
